DROP DATABASE IF EXISTS sd-capstone; /* I may remove this I didn't come here to be judged*/

CREATE DATABASE IF NOT EXISTS sd-capstone;

USE sd-capstone;

CREATE TABLE IF NOT EXISTS products (
  product_id INT DEFAULT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT NOT NULL,
  slogan VARCHAR(128) DEFAULT NOT NULL,
  description TEXT DEFAULT NOT NULL,
  category VARCHAR(64) DEFAULT NOT NULL,
  default_price INT DEFAULT NOT NULL,
);

CREATE TABLE IF NOT EXISTS features (
  feature_id INT DEFAULT AUTO_INCREMENT PRIMARY KEY,
  feature VARCHAR(64) DEFAULT,
  value VARCHAR(64) DEFAULT
);

CREATE TABLE IF NOT EXISTS styles (
  style_id INT DEFAULT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) DEFAULT NOT NULL,
  original_price INT DEFAULT NOT NULL,
  sale_price INT DEFAULT NOT NULL,
  'default?' BOOLEAN,
  FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE IF NOT EXISTS skus (
  sku_id INT DEFAULT AUTO_INCREMENT PRIMARY KEY,
  quantity INT DEFAULT NOT NULL,
  size VARCHAR(5),
  FOREIGN KEY (style_id) REFERENCES styles(style_id)
);

CREATE TABLE IF NOT EXISTS photos (
  photo_id INT DEFAULT AUTO_INCREMENT PRIMARY KEY,
  thumbnail_url VARCHAR(255) DEFAULT,
  'url' VARCHAR(255) DEFAULT,
  FOREIGN KEY (style_id) REFERENCES styles(style_id)
);

CREATE TABLE IF NOT EXISTS features (

);